
happyr.google_site_authenticator.index:
  path: '/authenticate-google'
  defaults: { _controller: HappyrGoogleSiteAuthenticatorBundle:Admin:index}

happyr.google_site_authenticator.authenticate:
  path: '/authenticate-google/authenticate/{name}'
  defaults: { _controller: HappyrGoogleSiteAuthenticatorBundle:Admin:authenticate}

happyr.google_site_authenticator.revoke:
  path: '/authenticate-google/revoke/{name}'
  defaults: { _controller: HappyrGoogleSiteAuthenticatorBundle:Admin:revoke}

happyr.google_site_authenticator.remove:
  path: '/authenticate-google/revoke/{name}'
  defaults: { _controller: HappyrGoogleSiteAuthenticatorBundle:Admin:remove}

happyr.google_site_authenticator.return_url:
  path: '/authenticate-google/return-url'
  defaults: { _controller: HappyrGoogleSiteAuthenticatorBundle:Admin:return}