parameters:

services:
  happyr.google_site_authenticator.token_config:
    class: Happyr\GoogleSiteAuthenticatorBundle\Model\TokenConfig
    arguments: [~]

  happyr.google_site_authenticator.client_provider:
    class: Happyr\GoogleSiteAuthenticatorBundle\Service\ClientProvider
    arguments: [@happyr.google_site_authenticator.token_config, ~]

  happyr.google.client_provider:
    alias: happyr.google_site_authenticator.client_provider

  happyr.google_site_authenticator.client:
    class: Google_Client
    factory: [@happyr.google_site_authenticator.client_provider, getClient]
    arguments: [~]
