parameters:
#    happyr_birthday.example.class: Happyr\GoogleSiteAuthenticatorBundle\Example

services:
  happyr.google_site_authenticator.client_provider_config:
    class: Happyr\GoogleSiteAuthenticatorBundle\Model\ClientProviderConfig
    public: false
    arguments: []

  happyr.google_site_authenticator.client_provider:
    class: Happyr\GoogleSiteAuthenticatorBundle\Service\ClientProvider
    arguments: [@happyr.google_site_authenticator.client_provider_config, ~]

    