
services:

  happyr.google_site_authenticator.storage.file:
    class: Happyr\GoogleSiteAuthenticatorBundle\Storage\FileStorage
    arguments: []

  happyr.google_site_authenticator.storage.cache:
    class: Happyr\GoogleSiteAuthenticatorBundle\Storage\FileStorage
    arguments: []

